#!/usr/bin/env php

<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application();

$app->add(new \Command\FileFinderCommand());
$app->add(new \Command\TranslatorStatusCommand());
$app->add(new \Command\TranslatorGenerateCommand());
$app->add(new \Command\TranslatorDiffCommand());

$app->run();